### ISSUE TITLE
Develop botnet

### ISSUE THREAD

**Issue by alix1011** [onionj/pybotnet#1]
Hi my friend, this project is great, but its options are few, I am waiting for amazing updates and adding options for keylogger, screenshot, download, upload, etc. Please develop the botnet.

**Comment by onionj** [comment]
Hello my friend **:)**
I'm glad you liked this _project_
I will do my best to add the requested options as soon as possible

**Comment by onionj** [comment]
export file to targets system added in v0.14 :) 👍 
usage:
`export_file <link_a_file>`

**Comment by alix1011** [comment]
Thank you my friend, good luck (:
I am proud to be able to help you in this project.
You need to develop a botnet and make it one of the best tools, the more options, the better.

**Comment by onionj** [comment]
Glad you want to contribute to this project  :D

**Comment by onionj** [comment]
i add project to pypi.org
so just:
`pip install pybotnet` :)

**Comment by alix1011** [comment]
Nice bro👍
