### ISSUE TITLE
Enhancment for pybotnet

### ISSUE THREAD

**Issue by SepehrRasouli** [onionj/pybotnet#23]
Hello again , Onionj. Pybotnet does a great job in solving the issue of Telegram being blocked in Iran , but this app is not only intended for Iranian's so I believe that using a proxy in countries where freedom of speech is respected might not be useful so we can make it an optional choice. What are your thoughts ?
SepehrRS

**Comment by onionj** [comment]
hi sepehr
Version 2.x is supposed to solve this problem
And we have an engine that can do this in several different ways :)

**Comment by SepehrRasouli** [comment]
Oh ok. thank you for responding.

**Comment by onionj** [comment]
YW :)
