### ISSUE TITLE
Transfer all functions to util.py

### ISSUE THREAD

**Issue by SepehrRasouli** [onionj/pybotnet#24]
Hi Onionj.
As a contributor, I've a hard time trying to write new features and I can't use the pybotnet's features so I've to kinda invent the wheel again every time I want to run a command and etc. 
I would be very happy if you consider transferring all the useful features and their functions to util.py so the contributors wouldn't have a hard time trying to write new and useful features.

**Comment by onionj** [comment]
hi sepehr
I will rewrite the code and try my best not to have these problems in the new version

**Comment by SepehrRasouli** [comment]
Thank a lot.
