### ISSUE TITLE
How do I setup.

### ISSUE THREAD

**Issue by TerranBen666** [onionj/pybotnet#28]
What version of python does it require and also when I open setup.py it instantly closes

**Comment by onionj** [comment]
hi
install pybotnet version 2 by: `pip3 install pybotnet -U --pre`

Document version 2 is not ready yet
But if you want to use version two, you can read the simple.py file.

**Comment by onionj** [comment]
and I have not tested version 2 on Windows yet ..!

**Comment by TerranBen666** [comment]
I was using windows at first lol im using unbuntu now and btw is pip install python3 going to give it the correct python version

**Comment by TerranBen666** [comment]
Ok thanks for your hel

**Comment by onionj** [comment]
you're welcome

**Comment by TerranBen666** [comment]
How can I run the setup.py and stuff on linux I mainly use windows and barely use linux. I know you do like cd and then find the directory the file is located, but what command do I do to run it

**Comment by SepehrRasouli** [comment]
You can use cd on windows too, cd is used to move to another directory.
What is your problem specifically ?

**Comment by TerranBen666** [comment]
when I open the main.py it instaly shuts and also I can't figure out how to run the .sh filese

**Comment by TerranBen666** [comment]
also do you have discord mine is Blx#0001

**Comment by SepehrRasouli** [comment]
Can you send your main.py ? I want to see the configurations you've done, You can anonymize the telegram keys.
And no, Unfortunately, I don't have Discrod.

**Comment by TerranBen666** [comment]
I haven't confinurged it at all because I can't run the install.sh on windows or even open the main.py

**Comment by SepehrRasouli** [comment]
Can you run "simple.py" ? .sh files are shell files which are for linux, you can't run them on Windows.

**Comment by TerranBen666** [comment]
I ran simple.py and it made a folder pycache

**Comment by SepehrRasouli** [comment]
That's OK, Please rename "configs.py.sample" to "configs.py" and add your own configs, Then try running "simple.py" again.

**Comment by TerranBen666** [comment]
Do I need to add configs? or are there already a base set of them or could you share yours to me?

**Comment by SepehrRasouli** [comment]
Yes you need to add configs, These configs are your bot token and your user id so PyBotNet could communicate with the Telegram API and send messages to you.
You don't need to send the configs to me, just make sure that they are correct, There is a good guide in "configs.py.sample" you can use.

**Comment by TerranBen666** [comment]
Ok thanks and I can use a telegram channel to control the bots?

**Comment by TerranBen666** [comment]
and I also re ran simple confing now do I open main.py?

**Comment by SepehrRasouli** [comment]
PyBotNet does not support this feature currently, but you can write your own script and modify PyBotNet to work the way you want.


> and I also re ran simple confing now do I open main.py?

You shouldn't run config.py, you need to enter your "bot-token"  and "user-id" there and then run "simple.py"
You can use the guide in configs.py to understand what credentials you need to enter.
Make sure that you've entered the correct credentials and have changed "configs.py.sample" to "configs.py"

**Comment by TerranBen666** [comment]
Yeah i added my bot token and my user id in the configs.py and i reran simple.py. what do i do next? Like to i have to make my own menu ans builder?

**Comment by SepehrRasouli** [comment]
No You don't, You should see if your telegram bot works now. Please refer to the [documentation](https://onionj.github.io/pybotnet/), From there you can understand what you should do next.

**Comment by TerranBen666** [comment]
Thsnks i will try

**Comment by SepehrRasouli** [comment]
Are you sure your configuration is correct ?

**Comment by SepehrRasouli** [comment]
Please try these commands :
`pip3 install pybotnet -U --pre`
`python3 -m pybotnet -t [TELEGRAM_TOKEN] -i [ADMIN_CHAT_ID] -n [BOT NAME]`
and then try /who in your bot.

**Comment by TerranBen666** [comment]
Is my telegram api token the bot token? or how do i get the telegram api token

**Comment by SepehrRasouli** [comment]
Please refer to the [documentation](https://onionj.github.io/pybotnet/) Or read the guide in the config file, From there you will find what to do next.

**Comment by TerranBen666** [comment]
I still don't understand what I'm doing wrong I followed the documentaion and stuff.

When I try to run the main.py i get a error that says python3: can't open file 'C:\\Users\\benwz\\Desktop\\pybotnet-master\\main.py': [Errno 2] No such file or directory (im using cmd)

I also tried /who and it didn't work

Do i need a group chat for this to work or something

**Comment by TerranBen666** [comment]
all of that as one command?

**Comment by TerranBen666** [comment]
when I run the second one it says there is no module named pybotnet

**Comment by SepehrRasouli** [comment]
Try this instead: 
`pip install pybotnet -U --pre`
`python3 -m pybotnet -t [TELEGRAM_TOKEN] -i [ADMIN_CHAT_ID] -n [BOT NAME]`

**Comment by SepehrRasouli** [comment]
No, You can enter them in any directory you want.

**Comment by TerranBen666** [comment]
Still dosen't work do you want screenshot so I can show yo?

**Comment by SepehrRasouli** [comment]
Yes, Please provide a screenshot of the error.

**Comment by TerranBen666** [comment]
![error](https://user-images.githubusercontent.com/75637878/176406920-b64b26f8-7ae6-459d-9698-351223ae30a7.png)

**Comment by TerranBen666** [comment]
What can I do?

**Comment by SepehrRasouli** [comment]
Please enter your Telegram-token , admin-chat-id and bot-name in the placeholders !!
Also, Please delete the clone of pybotnet you have, re-clone it again, rename configs.py.sample to configs.py, enter your credentials there, and then try running ./simple.py again.
Please read the guides carefully !

**Comment by TerranBen666** [comment]
Alright Thank you! I will try

**Comment by SepehrRasouli** [comment]
It's ok, Did you run `python ./simple.py` after cloning the project entering you proper credentials ? If not, Please do.
*Note : You should run this command in the pybotnet directory.*

**Comment by TerranBen666** [comment]
I get a error when I enter that command LOL

**Comment by TerranBen666** [comment]
![error 2](https://user-images.githubusercontent.com/75637878/176411084-28aa249d-2955-484e-973a-681dec9252d8.png)

**Comment by TerranBen666** [comment]
ok thanks I will thank you for your support :)

**Comment by SepehrRasouli** [comment]
From what i can see, the problem is not with PyBotNet, Unfortunately I can't reproduce your problem to help you any further.
Your credentials are either wrong, or your computer cannot contact telegram.

**Comment by TerranBen666** [comment]
Is my botoken correct or could you send me your files or at least send them and remove the stuff from the config

**Comment by TerranBen666** [comment]
How can i get my admin chat id? Maybe I'm doing that wrong, do i need to make a groupchat or something?

**Comment by SepehrRasouli** [comment]
No, you need to get your TELEGRAM_TOKEN from @botfather and Your ADMIN_CHAT_ID from @userinfobot.

**Comment by TerranBen666** [comment]
Yeah  I know that and when you create a bot you get the telegram token, but when i finsh editing the config do I msg @botfather /who? and also my ADMIN_CHAT_ID I have

**Comment by SepehrRasouli** [comment]
No, Literally, The document is saying it clearly that you've to message the bot you've created, not botfather !

**Comment by TerranBen666** [comment]
Alright i messaged it, dosen't work well I guess idk what to do so thanks for your help though maybe one day

**Comment by SepehrRasouli** [comment]
Sorry i wasn't able to help you
Good luck.

**Comment by onionj** [comment]
> ![error](https://user-images.githubusercontent.com/75637878/176406920-b64b26f8-7ae6-459d-9698-351223ae30a7.png)

in this screenshot, you run `pip install pybotnet -U --pre` in python 3.9, but run this command: `python3 -m pybotnet -t [TELEGRAM_TOKEN] -i [ADMIN_CHAT_ID] -n [BOT NAME]` in python 3.10

**Comment by TerranBen666** [comment]
okay thank you

**Comment by TerranBen666** [comment]
onionj. Do you have a discord or something i can contact you and chat easier maybe telegram. I tried what you told me and it still didn't work it would be easier

**Comment by onionj** [comment]
I think you did not understand the concept,
botnet needs a Telegram bot to be able to send you messages or take your commands
That's why we make a Telegram bot and give the token of that bot to the botnet
You also give your ID to your botnet so that it can send you messages

----

You don't need to clone the code from GitHub!

You can install pybotnet by run this command:

`python3 -m pip install pybotnet -U --pre`

and run a pybotnet:

for example if my telegram token is: `5226760482:AAGweoNtLrHEsasxnklwhjms78ytPS3U8gEO6asc`
and my chat id is : `5590231667`
 i can run botnet by:
`python3 -m pybotnet -t 5226760482:AAGweoNtLrHEsasxnklwhjms78ytPS3U8gEO6asc -i 5590231667 -v`

When your botnet runs, send a message to the same Telegram bot that you gave the token to botnet

for example send `\help` or `\who`
