### ISSUE TITLE
I have a problem running the file main.py

### ISSUE THREAD

**Issue by pbthong** [onionj/pybotnet#33]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/pybotnet/pybotnet/__main__.py", line 3, in <module>
    from . import *
ImportError: attempted relative import with no known parent package

**Comment by SepehrRasouli** [comment]
Hi @pbthong, You shouldn't run the main.py file. Please refer to the documentation on how to run your first pybotnet.

**Comment by pbthong** [comment]
What file should I send to the victim?

**Comment by SepehrRasouli** [comment]
You need to make your own pybotnet, The documentation has covered how to do this completely.

**Comment by onionj** [comment]
Read this document page: https://onionj.github.io/pybotnet/tutorial_user_guide/running_pybotnet_without_coding/

**Comment by pbthong** [comment]
Thanks bro!
do you have a botnet that takes cookies

Vào 1:43, Th 2, 8 thg 8, 2022 Saman Nezafat ***@***.***> đã
viết:

**Comment by onionj** [comment]
> do you have a botnet that takes cookies

no i am not having a botnet for get cookies.
