### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Rezahackm** [onionj/pybotnet#35]
Hi, I couldn't create main.py for myself, how should I add voice recorder and screen recorder to my file or add key logger or Google cookie logger?
please help me

**Comment by SepehrRasouli** [comment]
Hi @Rezahackm, Please read the documentation !. It is completely explained there.

**Comment by Rezahackm** [comment]
I read it, but I didn't understand what to do. Can you give me your telegram ID and guide me?

**Comment by SepehrRasouli** [comment]
Please keep all the conversation over here. 
The documentation has enough guidance to help you make your pybotnet, Please read it, If you stil can't understand it, Ask your questions here.
