### ISSUE TITLE
it's a Keylogger don't download it!

### ISSUE THREAD

**Issue by KingKrex69** [onionj/pybotnet#41]

**Comment by onionj** [comment]
I tested the code now and it worked correctly.

You can get the keylogger file with another command, and it's `/get_file klog.txt`

**Comment by SepehrRasouli** [comment]
Closing this as this issue is completely irrelevant. 
You are literally downloading a program to create a Trojan with it, For sure it has a keylogger as a built-in functionality, But it doesn't spy on you, It spies on your victims. Please read the documentation.
