### ISSUE TITLE
response from command /who not receiving in the console

### ISSUE THREAD

**Issue by andrewessel** [onionj/pybotnet#54]
I followed every step correclty using the 'without coding' method. I import pybotnet in my script and ran with python3 the syntax from the doc -> python3 -m pybotnet -t 'my token' -i 'id' -n 'bot name'. The result from my IDE was apparently OK because it passed to status 'running' but after I ran /who I received 'unrecognized command'

![pybotnet](https://github.com/onionj/pybotnet/assets/126993861/ad2c1385-2546-4e32-a50c-caceb80241b5)

**Comment by onionj** [comment]
Hi andro

I understand the issue now. It seems there was a misunderstanding. The "/who" command should be sent to your Telegram bot, not to BotFather. Please make sure to open a chat with your bot and send the "/who" command there. BotFather is only used for configuring your bot and managing its settings, but commands should be sent directly to your bot on Telegram.

Additionally, if you encounter any issues, you can run PyBotNet with the "-d" switch for debugging. This will provide more detailed information about what might be going wrong. For example:

```bash
python3 -m pybotnet -t [TELEGRAM_TOKEN] -i [ADMIN_CHAT_ID] -n [BOT NAME] -d
```

If you have any further questions or encounter any issues, feel free to ask for assistance.
