### ISSUE TITLE
SyntaxError: Invalid Decimal Literal

### ISSUE THREAD

**Issue by andreguiw** [onionj/pybotnet#62]
After adding my token I received an Invalid Decimal Literal for SyntaxError and the last digits after the hyphen were in red letters. So I'd kind hope you could explain me why python is saying that? What should I do to make the interpreter accept it??

**Comment by onionj** [comment]
Hi @andreguiw,

The error message "Invalid Decimal Literal for SyntaxError" typically indicates that there's an issue with how a decimal number is being represented in your code. Without seeing the specific line of code where the error occurs, it's a bit challenging to provide an exact solution. 

Remember, Python identifiers cannot start with a number. Ensure that any variable names or identifiers you're using in your code adhere to this rule.

If you can provide the specific line of code where the error occurs, or share more details about the context of your code and how you're using the token, I'd be happy to provide more targeted assistance.
